### ISSUE TITLE
OSS license?

### ISSUE THREAD

**Issue by mprast** [hamptonsmith/nearley-indentify#2]
Hey Hampton,
    This looks like a cool\useful project and I'd like to use it for some software I'm working on, but I can't safely do so from a legal perspective unless you add a license to it authorizing its reuse (e.g. the [MIT license](https://opensource.org/licenses/MIT) or the [GPL](https://opensource.org/licenses/GPL-3.0)). Do you have any plans to add a license? Happy also to help with a PR if needed. Thanks a ton!

    -Matt

**Comment by mprast** [comment]
@hamptonsmith friendly ping

**Comment by hamptonsmith** [comment]
Done!

**Comment by mprast** [comment]
:pray: thanks so much!
